# Generated by Django 3.2 on 2021-05-07 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_ch', models.CharField(blank=True, max_length=100)),
                ('abstract_ch', models.TextField(blank=True, max_length=2000)),
                ('keyword_en', models.CharField(blank=True, max_length=100)),
                ('abstract_en', models.TextField(blank=True, max_length=2000)),
                ('wendang', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ch', models.CharField(blank=True, max_length=100)),
                ('title_en', models.CharField(blank=True, max_length=100)),
                ('xueyuan', models.CharField(blank=True, max_length=100)),
                ('zhuanye', models.CharField(blank=True, max_length=100)),
                ('xuehao', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('laoshi', models.CharField(blank=True, max_length=100)),
                ('riqi', models.DateField()),
                ('outputname', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PaperAfter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bibliography', models.TextField(blank=True, max_length=1000)),
                ('acknowledgment', models.TextField(blank=True, max_length=1000)),
            ],
        ),
    ]
